// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpwuylZxbAqdTk31QcDLmMR0itHmyPT-w',
    appId: '1:509381864986:web:2c892256d2730bee7beba3',
    messagingSenderId: '509381864986',
    projectId: 'miketten-add57',
    authDomain: 'miketten-add57.firebaseapp.com',
    databaseURL: 'https://miketten-add57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'miketten-add57.firebasestorage.app',
    measurementId: 'G-C8BPJTKMW2',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuA7vBaSz37-jzXcrS-XB2Ls7eR_hRAdM',
    appId: '1:509381864986:android:d858652cec33e3557beba3',
    messagingSenderId: '509381864986',
    projectId: 'miketten-add57',
    databaseURL: 'https://miketten-add57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'miketten-add57.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkSHGxNXvm4iZuY-ZBOUqowkD9EvKbvSQ',
    appId: '1:509381864986:ios:daa89b8fe72a894f7beba3',
    messagingSenderId: '509381864986',
    projectId: 'miketten-add57',
    databaseURL: 'https://miketten-add57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'miketten-add57.firebasestorage.app',
    iosClientId: '509381864986-1hr53mgep1abc58laneldkppijj2a4pc.apps.googleusercontent.com',
    iosBundleId: 'com.maria.miketten.miKetten',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpwuylZxbAqdTk31QcDLmMR0itHmyPT-w',
    appId: '1:509381864986:web:2c892256d2730bee7beba3',
    messagingSenderId: '509381864986',
    projectId: 'miketten-add57',
    authDomain: 'miketten-add57.firebaseapp.com',
    databaseURL: 'https://miketten-add57-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'miketten-add57.firebasestorage.app',
    measurementId: 'G-C8BPJTKMW2',
  );
}
